In [1]:
import DBHandler as DBHandler
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoLocator, MaxNLocator
import sys

connection is ok


In [2]:
# Hier gehe ich davon aus, dass DBHandler.getMostPopularVideosByCountryAll()
# einen DataFrame mit den gewünschten Daten zurückgibt.
dataset = DBHandler.getMostPopularVideosByCountryAll()
dataset.sort_values(by="Like_Count", ascending=True, inplace=True)

# Split data into Features and Target
x_data = dataset[["Views", "Comment_Count", "Published_At"]]
y_data = dataset["Like_Count"]

# Concatenate features and target for the correlation matrix
data_for_corr = pd.concat([x_data, y_data], axis=1)

# Calculate the correlation matrix
corr_matrix = data_for_corr.corr()

# Print or visualize the correlation matrix
print(corr_matrix)

2024-03-29 15:57:47,284 INFO sqlalchemy.engine.Engine SELECT CAST(SERVERPROPERTY('ProductVersion') AS VARCHAR)
2024-03-29 15:57:47,287 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-03-29 15:57:47,295 INFO sqlalchemy.engine.Engine SELECT schema_name()
2024-03-29 15:57:47,296 INFO sqlalchemy.engine.Engine [generated in 0.00127s] ()
2024-03-29 15:57:47,312 INFO sqlalchemy.engine.Engine SELECT CAST('test max support' AS NVARCHAR(max))
2024-03-29 15:57:47,312 INFO sqlalchemy.engine.Engine [generated in 0.00089s] ()
2024-03-29 15:57:47,317 INFO sqlalchemy.engine.Engine SELECT 1 FROM fn_listextendedproperty(default, default, default, default, default, default, default)
2024-03-29 15:57:47,318 INFO sqlalchemy.engine.Engine [generated in 0.00090s] ()
2024-03-29 15:57:47,331 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-29 15:57:47,331 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE ([INFORMATION_SCHEMA].[TABLE

In [3]:
dataset = DBHandler.getMostPopularVideosByCountryAll()
dataset.sort_values(by="Views", ascending=True, inplace=True)

print(dataset.head())

# Split data into Features and Target
x_data = dataset.reset_index()[["Views", "Comment_Count", "Duration", "Subscriber_Count"]].to_numpy()
y_data = dataset.reset_index()["Like_Count"].to_numpy()

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.20, random_state=42)

2024-03-29 15:57:47,400 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-29 15:57:47,401 INFO sqlalchemy.engine.Engine SELECT [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] 
FROM [INFORMATION_SCHEMA].[TABLES] 
WHERE ([INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max)) OR [INFORMATION_SCHEMA].[TABLES].[TABLE_TYPE] = CAST(? AS NVARCHAR(max))) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_NAME] = CAST(? AS NVARCHAR(max)) AND [INFORMATION_SCHEMA].[TABLES].[TABLE_SCHEMA] = CAST(? AS NVARCHAR(max))
2024-03-29 15:57:47,403 INFO sqlalchemy.engine.Engine [cached since 0.07161s ago] ('BASE TABLE', 'VIEW', 'SELECT * FROM [dbo].[mostpopularvideosbycountry]', 'dbo')
2024-03-29 15:57:47,417 INFO sqlalchemy.engine.Engine SELECT * FROM [dbo].[mostpopularvideosbycountry]
2024-03-29 15:57:47,418 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-03-29 15:57:47,434 INFO sqlalchemy.engine.Engine ROLLBACK
    Country_Chart                                              Title  \
136            FR 

In [4]:
lm = LinearRegression()

lm.fit(x_train, y_train)

y_pred_lr = lm.predict(x_test)
r2 = r2_score(y_test, y_pred_lr)
mse = mean_squared_error(y_test, y_pred_lr)

print(x_train)

[[  119771       60       49   716000]
 [   99040       86     1358   109000]
 [  554432     1809     3083   626000]
 [   84773      545      993   137000]
 [  203270        0      164  1620000]
 [51089569     2222       14 14800000]
 [  281069      898     2025  2300000]
 [  142950      298      697   550000]
 [   57307      276      891   851000]
 [  162856      158     3527   154000]
 [25561421     9869       47   461000]
 [ 1382601     1882      191   477000]
 [ 1399789     6059     3071   425000]
 [  101701      173     3105   120000]
 [   84677      142      757   105000]
 [  947431     5869     2397  4800000]
 [13505152     4316       31 29800000]
 [17599470    46422     1503 19500000]
 [  781322     1050     1024  4850000]
 [ 4466628     1612       46  6630000]
 [ 2136069     8605      117 20400000]
 [ 3966554     8268     3846  8460000]
 [  579391       66       31   768000]
 [   36864      312      113   228000]
 [ 9511558     6031     1606 34400000]
 [  613922     1617     1

In [5]:
views = 299760
comments = 1973
duration = 1060

input_data = [[views, comments, duration]]

predicted_likes = lm.predict(input_data)

print(predicted_likes)

ValueError: X has 3 features, but LinearRegression is expecting 4 features as input.